### ISSUE TITLE
formatting....

### ISSUE THREAD

**Issue by proseLA** [marco-pm/zencart_instantsearch#20]
marco,
when are you going to come over the dark side and replace:
```
<?php echo $var; ?>
```
with:
```
<?= $var; ?>
```
so much easier to read with mixed php and html.

i use it in all my mods with no ill will.

**Comment by marco-pm** [comment]
I agree, but I prefer to adhere to ZC coding standards whenever possible... see https://docs.zen-cart.com/dev/contributing/coding_standards/#php-short-echo-tags
