### ISSUE TITLE
error in instant_search_dropdown.min.js: TypeError: First argument must be a string

### ISSUE THREAD

**Issue by torvista** [marco-pm/zencart_instantsearch#31]
If I search for a product that has a space as the third character (when it first begins the search), I get a console error:
![image](https://github.com/marco-pm/zencart_instantsearch/assets/4391026/8467956f-8dd1-4348-8d69-d5565886f2ac)

**Comment by marco-pm** [comment]
Thank you for finding and reporting this issue!

**Comment by torvista** [comment]
Ha, I was just looking at this and was about to comment that I had no chance of fixing this with a de-minified file!
Thanks.
