### ISSUE TITLE
Image alt/title text should be item's name not image-name

### ISSUE THREAD

**Issue by lat9** [marco-pm/zencart_instantsearch#34]
When the instant search brings up matching items, the alt/title text for the image is the name of the image, not the name of the item.  Suggest changing these lines
https://github.com/marco-pm/zencart_instantsearch/blob/7a832b48ff5b461eefc0abf809cc40540b01c601/includes/classes/ajax/zcAjaxInstantSearch.php#L281-L283

to
```php
            $dropdownResult['img'] = INSTANT_SEARCH_DROPDOWN_DISPLAY_IMAGE === 'true' && !empty($img)
                ? zen_image(DIR_WS_IMAGES . strip_tags($img), strip_tags($name), INSTANT_SEARCH_DROPDOWN_IMAGE_WIDTH, INSTANT_SEARCH_DROPDOWN_IMAGE_HEIGHT)
                : '';
```

**Comment by marco-pm** [comment]
Thanks @lat9!
