### ISSUE TITLE
Call for price/sold-out items result in wonky display

### ISSUE THREAD

**Issue by lat9** [marco-pm/zencart_instantsearch#35]
... since their 'price' (as of current zc158/zc200) contains a link to the product's ask-a-question page.  Suggest changing these lines
https://github.com/marco-pm/zencart_instantsearch/blob/7a832b48ff5b461eefc0abf809cc40540b01c601/includes/classes/ajax/zcAjaxInstantSearch.php#L236-L240

to read
```php
                $dropdownResult['price'] = INSTANT_SEARCH_DROPDOWN_DISPLAY_PRODUCT_PRICE === 'true'
                    ? !empty($result['products_displayed_price'])
                        ? $result['products_displayed_price']
                        : strip_tags(zen_get_products_display_price($id))
                    : '';
```

**Comment by lat9** [comment]
I dunno either, all I'm seeing is a broken display on the call-for-price products because there's that anchor-link.  FWIW, I'm running on the post-zc158a version of the final zc158 branch.

Agreed on just removing the link-tags instead of all HTML.  I _should_ have time next week to go back and see where that link comes from.

**Comment by marco-pm** [comment]
@lat9 any follow up? Otherwise I think I can close this issue.. thanks

**Comment by lat9** [comment]
I guess I didn't have the time.  Since no other reports have been made, I'll close this.
