### ISSUE TITLE
`TEXT_NO_PRODUCTS` overrides base `search` constant

### ISSUE THREAD

**Issue by lat9** [marco-pm/zencart_instantsearch#36]
In /includes/languages/english/extra_definitions/lang.instant_search.php, there's an empty-string definition for the base search pages' `TEXT_NO_PRODUCTS` which overrides any page-specific language definition resulting in no "No matching products found" message.

Is there a reason that that constant's defined that way?

**Comment by marco-pm** [comment]
I think I added it because `product_listing_instant_search.php` (used by the instant search results page) couldn't find that definition (it's loaded via ajax).
You are right though that it overrides all the other definitions.
Since that string is not even actually displayed, I found a better way...
