### ISSUE TITLE
 instant_search_dropdown.min.js modifies layout (Bootstrap)

### ISSUE THREAD

**Issue by torvista** [marco-pm/zencart_instantsearch#39]
Trying to get this to work with my Bootstrap template (I have copied the Bootstrap template files from the repository).

I have the search field wide across the top:
![image](https://github.com/marco-pm/zencart_instantsearch/assets/4391026/96774f58-b6e8-47ba-886f-23b3ab4f9bf9)

But once instant_search_dropdown.min.js is loaded, the search field gets reduced:
![image](https://github.com/marco-pm/zencart_instantsearch/assets/4391026/f9fd2ec6-2626-4d31-ba3c-a25432ca36b5)

Looking in the equivalent .tsx file, the only thing I could see being relevant was this:
```
if (resultsContainerDiv.clientWidth > 250) {
                setAdditionalClass(' instantSearchResultsDropdownContainer--lg');
```
But commenting-out these classes in the css, or increasing the >250 in the unminified code had no effect.

(I know Bootstrap has its own ajax search but that's a modal which I don't like/I prefer one search field to type into, and I had no initial success modifying that one to work on the native field/instead of the modal.)

**Comment by marco-pm** [comment]
Your navbar and `quick_find_header` form seems a bit different from the Bootstrap template default. Can you share your HTML and CSS for those?

**Comment by torvista** [comment]
pm sent

**Comment by marco-pm** [comment]
You changed the `quick_find_header` bootstrap class from `form-inline` to `w-100`.
In order for the search input to stretch horizontally just add `flex-grow: 1;` to `.instantSearchInputWrapper` in `stylesheet_instant_search.css`.
It's just a matter of custom css anyway, no changes are needed to the code so I'm closing this issue

**Comment by torvista** [comment]
Thanks, pardon my ignorance, I don't find Bootstrap css intuitive at all...it's effects are never as I expect.
