### ISSUE TITLE
"Unrelated" results due to SOUNDS LIKE

### ISSUE THREAD

**Issue by torvista** [marco-pm/zencart_instantsearch#7]
In my particular case, I was getting a lot of seemingly incorrect results.
This was due to this
(LEFT(pd.products_name, LENGTH(:wordSearch:)) SOUNDS LIKE :wordSearch:)" .
which I have removed for my purposes.
Not a complaint, just thought I'd point it out if others look for info on this.
Possible this could be an admin option?

**Comment by marco-pm** [comment]
Yeah, I think there are some use cases where that condition leads to unwanted results.
